import Nav from '@/components/Nav'
import Head from 'next/head'
import Image from 'next/image'
import doces from '../../public/doces.jpg'
import aline from '../../public/aline.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Line Doceria Artesanal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Poppins:wght@400;500;700&display=swap" rel="stylesheet" />
        <script src="https://unpkg.com/phosphor-icons"></script>
      </Head>

      <header id="header">
        <Nav />
      </header>

      <main>
        <section className="section" id="home">
          <div className="container grid">
            <div className="image">
              <Image src={doces} />
            </div>

            <div className="text">
              <h2 className="title">Experimente melhor da confeitaria artesanal</h2>

              <p>Doces, Bolos, Brownies, Palhas Italianas, Trufas, e muito mais para adoçar momentos especiais!</p>

              <a className="button" href="#menu">Veja o Cardápio</a>
            </div>
          </div>
        </section>

        <div class="divider-1"></div>

        <section className="section" id="about">
          <div className="container grid">
            <div className="image">
              <Image src={aline} />
            </div>

            <div className="text">
              <h2 className="title">Sobre nós</h2>

              <p>
                Olá! Eu sou a Aline, a confeiteira por trás da <strong>Line Doceria Artesanal. ❤</strong>
              </p>

              <br />

              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure
                illum ratione impedit quae eum quis adipisci asperiores, est
                doloribus distinctio excepturi minima eius dolore! Perferendis
                laborum illo aspernatur repellendus ipsum.
              </p>

              <br />

              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed
                exercitationem, illum sapiente quasi hic iusto odio maiores esse
                quaerat quis necessitatibus at odit, dolores dicta, officia ab
                quos. Provident, quae.
              </p>
            </div>
          </div>
        </section>

        <div className="divider-2"></div>

        <section className="section" id="services">
          <div className="container grid">
            <header>
              <h2 className="title">Nossos serviços</h2>
              <p className="subtitle">
                A <strong>Line Doceria Artesanal</strong> oferece os melhores serviços e os mais
                saborosos produtos de confeitaria, seja para o seu evento ou simplesmente para adoçar a sua rotina. ❤
              </p>
            </header>
            <div className="cards grid">
              <div className="card">
                <i class="ph-bag"></i>
                <h3 className="title">Pequenas e grandes quantidades</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit
                  distinctio neque blanditiis, dolorem aperiam nulla explicabo
                  asperiores
                </p>
              </div>
              <div className="card">
                <i class="ph-cake"></i>
                <h3 className="title">Produtos personalizados</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit
                  distinctio neque blanditiis, dolorem aperiam nulla explicabo
                  asperiores
                </p>
              </div>
              <div className="card">
                <i class="ph-bicycle"></i>
                <h3 className="title">Fazemos entregas</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit
                  distinctio neque blanditiis, dolorem aperiam nulla explicabo
                  asperiores
                </p>
              </div>
            </div>
          </div>
        </section>

        <div class="divider-1"></div>
      </main>
    </>
  )
}
